[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x524f67"
text = "0xe0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 5

[general]
live_config_reload = true
